ALTER TABLE doctors DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE hero_banners DISABLE ROW LEVEL SECURITY;
ALTER TABLE mading_content DISABLE ROW LEVEL SECURITY;
ALTER TABLE popups DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_facilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE mcu_packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE careers_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE careers_registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;

SELECT 'RLS disabled for all tables' as status;
