DROP POLICY IF EXISTS "Public read doctors" ON doctors;
DROP POLICY IF EXISTS "Public read schedules" ON schedules;
DROP POLICY IF EXISTS "Public read hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Public read mading_content" ON mading_content;
DROP POLICY IF EXISTS "Public read popups" ON popups;
DROP POLICY IF EXISTS "Public read room_types" ON room_types;
DROP POLICY IF EXISTS "Public read room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Public read room_images" ON room_images;
DROP POLICY IF EXISTS "Public read mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Public read careers_config" ON careers_config;
DROP POLICY IF EXISTS "Public read careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Anyone can create career registration" ON careers_registrations;
DROP POLICY IF EXISTS "Admin read own profile" ON admin_users;
DROP POLICY IF EXISTS "Admin update all doctors" ON doctors;
DROP POLICY IF EXISTS "Admin insert all doctors" ON doctors;
DROP POLICY IF EXISTS "Admin delete all doctors" ON doctors;
DROP POLICY IF EXISTS "Admin update all schedules" ON schedules;
DROP POLICY IF EXISTS "Admin insert all schedules" ON schedules;
DROP POLICY IF EXISTS "Admin delete all schedules" ON schedules;
DROP POLICY IF EXISTS "Admin update all hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin insert all hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin delete all hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin update all mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin insert all mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin delete all mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin update all popups" ON popups;
DROP POLICY IF EXISTS "Admin insert all popups" ON popups;
DROP POLICY IF EXISTS "Admin delete all popups" ON popups;
DROP POLICY IF EXISTS "Admin update all room_types" ON room_types;
DROP POLICY IF EXISTS "Admin insert all room_types" ON room_types;
DROP POLICY IF EXISTS "Admin delete all room_types" ON room_types;
DROP POLICY IF EXISTS "Admin update all room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin insert all room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin delete all room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin update all room_images" ON room_images;
DROP POLICY IF EXISTS "Admin insert all room_images" ON room_images;
DROP POLICY IF EXISTS "Admin delete all room_images" ON room_images;
DROP POLICY IF EXISTS "Admin update all mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin insert all mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin delete all mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin update all careers_config" ON careers_config;
DROP POLICY IF EXISTS "Admin insert all careers_config" ON careers_config;
DROP POLICY IF EXISTS "Admin update all careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Admin delete all careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Admin full access admin_users" ON admin_users;
DROP POLICY IF EXISTS "Admin insert hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin update hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin delete hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Admin insert doctors" ON doctors;
DROP POLICY IF EXISTS "Admin update doctors" ON doctors;
DROP POLICY IF EXISTS "Admin delete doctors" ON doctors;
DROP POLICY IF EXISTS "Admin insert schedules" ON schedules;
DROP POLICY IF EXISTS "Admin update schedules" ON schedules;
DROP POLICY IF EXISTS "Admin delete schedules" ON schedules;
DROP POLICY IF EXISTS "Admin insert mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin update mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin delete mading_content" ON mading_content;
DROP POLICY IF EXISTS "Admin insert popups" ON popups;
DROP POLICY IF EXISTS "Admin update popups" ON popups;
DROP POLICY IF EXISTS "Admin delete popups" ON popups;
DROP POLICY IF EXISTS "Admin insert room_types" ON room_types;
DROP POLICY IF EXISTS "Admin update room_types" ON room_types;
DROP POLICY IF EXISTS "Admin delete room_types" ON room_types;
DROP POLICY IF EXISTS "Admin insert room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin update room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin delete room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Admin insert room_images" ON room_images;
DROP POLICY IF EXISTS "Admin update room_images" ON room_images;
DROP POLICY IF EXISTS "Admin delete room_images" ON room_images;
DROP POLICY IF EXISTS "Admin insert mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin update mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin delete mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Admin insert careers_config" ON careers_config;
DROP POLICY IF EXISTS "Admin update careers_config" ON careers_config;
DROP POLICY IF EXISTS "Admin update careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Admin delete careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Allow all insert hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Allow all update hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Allow all delete hero_banners" ON hero_banners;
DROP POLICY IF EXISTS "Allow all insert doctors" ON doctors;
DROP POLICY IF EXISTS "Allow all update doctors" ON doctors;
DROP POLICY IF EXISTS "Allow all delete doctors" ON doctors;
DROP POLICY IF EXISTS "Allow all insert schedules" ON schedules;
DROP POLICY IF EXISTS "Allow all update schedules" ON schedules;
DROP POLICY IF EXISTS "Allow all delete schedules" ON schedules;
DROP POLICY IF EXISTS "Allow all insert mading_content" ON mading_content;
DROP POLICY IF EXISTS "Allow all update mading_content" ON mading_content;
DROP POLICY IF EXISTS "Allow all delete mading_content" ON mading_content;
DROP POLICY IF EXISTS "Allow all insert popups" ON popups;
DROP POLICY IF EXISTS "Allow all update popups" ON popups;
DROP POLICY IF EXISTS "Allow all delete popups" ON popups;
DROP POLICY IF EXISTS "Allow all insert room_types" ON room_types;
DROP POLICY IF EXISTS "Allow all update room_types" ON room_types;
DROP POLICY IF EXISTS "Allow all delete room_types" ON room_types;
DROP POLICY IF EXISTS "Allow all insert room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Allow all update room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Allow all delete room_facilities" ON room_facilities;
DROP POLICY IF EXISTS "Allow all insert room_images" ON room_images;
DROP POLICY IF EXISTS "Allow all update room_images" ON room_images;
DROP POLICY IF EXISTS "Allow all delete room_images" ON room_images;
DROP POLICY IF EXISTS "Allow all insert mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Allow all update mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Allow all delete mcu_packages" ON mcu_packages;
DROP POLICY IF EXISTS "Allow all insert careers_config" ON careers_config;
DROP POLICY IF EXISTS "Allow all update careers_config" ON careers_config;
DROP POLICY IF EXISTS "Allow all update careers_registrations" ON careers_registrations;
DROP POLICY IF EXISTS "Allow all delete careers_registrations" ON careers_registrations;

CREATE POLICY "allow_select_doctors" ON doctors FOR SELECT USING (true);
CREATE POLICY "allow_insert_doctors" ON doctors FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_doctors" ON doctors FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_doctors" ON doctors FOR DELETE USING (true);

CREATE POLICY "allow_select_schedules" ON schedules FOR SELECT USING (true);
CREATE POLICY "allow_insert_schedules" ON schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_schedules" ON schedules FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_schedules" ON schedules FOR DELETE USING (true);

CREATE POLICY "allow_select_hero_banners" ON hero_banners FOR SELECT USING (true);
CREATE POLICY "allow_insert_hero_banners" ON hero_banners FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_hero_banners" ON hero_banners FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_hero_banners" ON hero_banners FOR DELETE USING (true);

CREATE POLICY "allow_select_mading_content" ON mading_content FOR SELECT USING (true);
CREATE POLICY "allow_insert_mading_content" ON mading_content FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_mading_content" ON mading_content FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_mading_content" ON mading_content FOR DELETE USING (true);

CREATE POLICY "allow_select_popups" ON popups FOR SELECT USING (true);
CREATE POLICY "allow_insert_popups" ON popups FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_popups" ON popups FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_popups" ON popups FOR DELETE USING (true);

CREATE POLICY "allow_select_room_types" ON room_types FOR SELECT USING (true);
CREATE POLICY "allow_insert_room_types" ON room_types FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_room_types" ON room_types FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_room_types" ON room_types FOR DELETE USING (true);

CREATE POLICY "allow_select_room_facilities" ON room_facilities FOR SELECT USING (true);
CREATE POLICY "allow_insert_room_facilities" ON room_facilities FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_room_facilities" ON room_facilities FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_room_facilities" ON room_facilities FOR DELETE USING (true);

CREATE POLICY "allow_select_room_images" ON room_images FOR SELECT USING (true);
CREATE POLICY "allow_insert_room_images" ON room_images FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_room_images" ON room_images FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_room_images" ON room_images FOR DELETE USING (true);

CREATE POLICY "allow_select_mcu_packages" ON mcu_packages FOR SELECT USING (true);
CREATE POLICY "allow_insert_mcu_packages" ON mcu_packages FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_mcu_packages" ON mcu_packages FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_mcu_packages" ON mcu_packages FOR DELETE USING (true);

CREATE POLICY "allow_select_careers_config" ON careers_config FOR SELECT USING (true);
CREATE POLICY "allow_insert_careers_config" ON careers_config FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_careers_config" ON careers_config FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "allow_select_careers_registrations" ON careers_registrations FOR SELECT USING (true);
CREATE POLICY "allow_insert_careers_registrations" ON careers_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_careers_registrations" ON careers_registrations FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_careers_registrations" ON careers_registrations FOR DELETE USING (true);

CREATE POLICY "allow_select_admin_users" ON admin_users FOR SELECT USING (true);
CREATE POLICY "allow_insert_admin_users" ON admin_users FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_update_admin_users" ON admin_users FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "allow_delete_admin_users" ON admin_users FOR DELETE USING (true);

SELECT 'All RLS policies reset and recreated successfully!' as status;
